### ISSUE TITLE
limited environment names for projects?

### ISSUE THREAD

**Issue by sanguis** [Knectar/behat-ci#5]
when creating projects on the behat-ci projects.yml

I created 

``` yml
foo:
  environments:
  ## should match the branch
    dev:
        base_url: https://user:password@foo.dev.bar.com
    production:
        base_url: https://www.foo.com
    stage:
      base_url: https://user:password@stage.foo.com
  profiles: #to run as set in profiles.yml
    - iPhone
    - mac-safari
```

When trying to queue the environment for changes I was told that 'stage' was not an option.

Applications can have many instances with arbitrary names. so the app needs more flexibility in that.
